management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    instances:
      shippingRetry:
        maxRetryAttempts: 3
        waitDuration: 100ms
  circuitbreaker:
    instances:
      shippingCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 1s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10
      inventoryCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 1s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10